# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52cbea85686eb5f45d857586c2c9da8d"
application_url = "https://teeth-cultures-packing-deep.trycloudflare.com"
embedded = true
name = "densumes-search-extension"
handle = "densumes-search-extension"

[build]
include_config_on_deploy = true
dev_store_url = "trieveai.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://teeth-cultures-packing-deep.trycloudflare.com/auth/callback",
  "https://teeth-cultures-packing-deep.trycloudflare.com/auth/shopify/callback",
  "https://teeth-cultures-packing-deep.trycloudflare.com/api/auth/callback",
]

[pos]
embedded = false
