# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d9ffd6335a93c6424551710a1936362"
application_url = "https://salvation-beam-costa-enhance.trycloudflare.com"
embedded = true
name = "cdxker-search-extension"
handle = "cdxker-search-extension"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://salvation-beam-costa-enhance.trycloudflare.com/auth/callback",
  "https://salvation-beam-costa-enhance.trycloudflare.com/auth/shopify/callback",
  "https://salvation-beam-costa-enhance.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
