# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8765d78a52aa8c12ae2d235d9d41529c"
application_url = "https://theology-blocked-effect-others.trycloudflare.com"
embedded = true
name = "trieve-search-extension"
handle = "trieve-search-extension"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/app/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/app/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/app/products/delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://theology-blocked-effect-others.trycloudflare.com/auth/callback",
  "https://theology-blocked-effect-others.trycloudflare.com/auth/shopify/callback",
  "https://theology-blocked-effect-others.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "trieveai.myshopify.com"
include_config_on_deploy = true
