kind: Service
apiVersion: v1
metadata:
  name: search-service
  labels:
    app.kubernetes.io/name: search-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 80
      protocol: TCP
      name: search
  selector:
    app.kubernetes.io/name: search
    app.kubernetes.io/instance: {{ .Release.Name }}
