version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_editor
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  script-redis:
    image: redis
    container_name: my-script-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - script-redis-data:/data

  qdrant-database:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/data

  s3:
    image: minio/minio
    ports:
      - 9000:9000
      - 42625:42625
    environment:
      - MINIO_ROOT_USER=rootuser
      - MINIO_ROOT_PASSWORD=rootpassword
    volumes:
      - s3-data:/data
    command: server --console-address ":42625" /data

volumes:
  redis-data:
  script-redis-data:
  pgdata:
  qdrant_data:
  s3-data:
