version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vault
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vault-network

  redis:
    image: redis
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vault-network

  script-redis:
    image: redis
    container_name: my-script-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - script-redis-data:/data
    networks:
      - vault-network

  qdrant-database:
    image: qdrant/qdrant:v1.3.2
    environment:
      - QDRANT__SERVICE__API_KEY=qdrant_pass
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - vault-network

  s3:
    image: minio/minio
    ports:
      - 9000:9000
      - 42625:42625
    environment:
      - MINIO_ROOT_USER=rootuser
      - MINIO_ROOT_PASSWORD=rootpassword
    volumes:
      - s3-data:/data
    command: server --console-address ":42625" /data
    networks:
      - vault-network
  vault-server:
    image: arguflow/vault-server
    build: ./server/
    networks:
      - vault-network
    ports:
      - 8090:8090
    environment:
      - REDIS_URL=${REDIS_URL}
      - QDRANT_URL=${QDRANT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - S3_ACCESS_KEY=ZiuIuCVAJDj5zCbxBhLC
      - S3_SECRET_KEY=rnHShpEzoInB5blpD1XE6R8iSdojGWbXHTHjE3qz
      - S3_BUCKET=vault
      - OPENAI_API_KEY=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
    depends_on:
      - s3
      - qdrant-database
      - redis
      - db
  vault-chat:
    image: arguflow/vault-chat
    build: ./chat/
    networks:
      - vault-network
    ports:
      - 3000:3000
    environment:
      - API_HOST=${API_HOST}
      - PUBLIC_HOST=http://127.0.0.1:3000
      - PUBLIC_API_HOST=http://vault-server:8090/api
  vault-search:
    image: arguflow/vault-search
    build: ./search/
    networks:
      - vault-network
    ports:
      - 3001:3000
    environment:
      - API_HOST=${API_HOST}
      - PUBLIC_HOST=http://127.0.0.1:3001
      - PUBLIC_API_HOST=${API_HOST}

networks:
  vault-network:
    driver: bridge

volumes:
  redis-data:
  script-redis-data:
  pgdata:
  qdrant_data:
  s3-data:
