commonLabels:
  app.kubernetes.io/component: worker-sync-qdrant
nameSuffix: -sync-qdrant
resources:
  - ../base
images:
  - name: worker
    newName: trieve/sync_qdrant
patches:
  - target:
      kind: Deployment
      name: trieve-worker
    patch: |-
      - op: add
        path: /spec/replicas
        value: 0 # this deployment functions more like a "Job"