{{ $storage := (ternary "10Gi" "500Gi" (eq .Values.environment  "local")) }}
{{- range $index, $service := .Values.embeddings }}
{{- $name := (get $service "name") }}
{{- if ne $index 0 }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-{{ $name }}-pvc
  labels:
    app.kubernetes.io/name: embedding-{{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce  
{{- if eq $.Values.environment "aws" }}
  storageClassName: gp2
{{- else }}
  storageClassName: ""  
{{- end }}
  resources:
    requests:
      storage: {{ $storage }}
{{- end }}
