{{- if eq $.Values.environment "local" }}
{{ $storage := (ternary "10Gi" "500Gi" (eq .Values.environment  "local")) }}
{{- range $index, $service := .Values.embeddings }}
{{- $name := (get $service "name") }}
{{- if ne $index 0 }}
---
{{- end }}
{{- $pvName := (printf "embedding-%s-pv" $name) }}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $pvName }}
spec:
    capacity:
        storage: {{ $storage }}
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ""
    hostPath:
      path: "/{{ $pvName }}"
{{- end }}
{{- end }}
