apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  labels:
    app.kubernetes.io/name: ingest
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.containers.ingest.replicas | default 10 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ingest
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: ingest
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: ingest
        securityContext:
          capabilities:
            add: ["SYS_PTRACE"]
        resources:
          {{- toYaml .Values.containers.server.resources | nindent 12 }}
        image: {{ printf "%s:%s" "trieve/ingest" .Values.containers.ingest.tag }}
        envFrom:
          - configMapRef:
              name: trieve-server-config
