---
{{- with $.Values.domains.chat }}
{{ if not .disabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-chat
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: {{ .class | default "gce" }}
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .class | default "gce" }}
  {{- if .tls }}
  tls:
    {{- range .tls}}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $.Values.domains.chat.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-service
                port:
                  number: 3000
{{- end }}
{{- end }}
---
{{- with $.Values.domains.server }}
{{ if not .disabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-server
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: {{ .class | default "gce" }}
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .class | default "gce" }}
  {{- if .tls }}
  tls:
    {{- range .tls}}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $.Values.domains.server.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 8090
{{- end }}
{{- end }}
---
{{- with $.Values.domains.search }}
{{ if not .disabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-search
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: {{ .class | default "gce" }}
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .class | default "gce" }}
  {{- if .tls }}
  tls:
    {{- range .tls}}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $.Values.domains.search.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 3001
{{- end }}
{{- end }}
---
{{- with $.Values.domains.dashboard }}
{{ if not .disabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dashboard
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: {{ .class | default "gce" }}
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .class | default "gce" }}
  {{- if .tls }}
  tls:
    {{- range .tls}}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $.Values.domains.dashboard.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-service
                port:
                  number: 3002
{{- end }}
{{- end }}
---
