{{- $name := "minio-service" }}
{{- $selector := "minio" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/instance: trieve
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: trieve-0.1.0
    meta.helm.sh/release-name: trieve
    meta.helm.sh/release-namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: minio
    - port: 42625
      targetPort: 42625
      protocol: TCP
      name: minio-secondary
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
