apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: minio
        image: {{ printf "%s%s:%s" (ternary (printf "%s.dkr.ecr.%s.amazonaws.com/" .Values.accountId .Values.region) "localhost:5000/" (eq .Values.environment "aws")) "minio" .Values.containers.minio.tag }}
        ports:
          - containerPort: 9000
          - containerPort: 42625
        volumeMounts:
          - name: minio-data
            mountPath: /data
        env:
          - name: MINIO_ROOT_USER
            value: {{ .Values.config.minio.rootUser }}
          - name: MINIO_ROOT_PASSWORD
            value: {{ .Values.config.minio.rootPassword }}
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
