apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: qdrant
        image: {{ printf "%s%s:%s" (ternary (printf "%s.dkr.ecr.%s.amazonaws.com/" .Values.accountId .Values.region) "localhost:5000/" (eq .Values.environment "aws")) "qdrant" .Values.containers.qdrant.tag }}
      ports:
        - containerPort: 6334
        - containerPort: 6333
      volumeMounts:
        - name: qdrant-data
          mountPath: /qdrant/storage
      env:
        - name: QDRANT__SERVICE__API_KEY
          value: {{ .Values.config.qdrant.apiKey }}
      volumes:
      - name: qdrant-data
        persistentVolumeClaim:
          claimName: qdrant-pvc
