{{- $name := "qdrant-service" }}
{{- $selector := "qdrant" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/instance: trieve
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: trieve-0.1.0
    meta.helm.sh/release-name: trieve
    meta.helm.sh/release-namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 6333
      targetPort: 6333
      protocol: TCP
      name: primary
    - port: 6334
      targetPort: 6334
      protocol: TCP
      name: secondary
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
