{{ $storage := (ternary "10Gi" "500Gi" (eq .Values.environment  "local")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  labels:
    app.kubernetes.io/name: s3
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce  
{{- if eq .Values.environment "aws" }}
  storageClassName: gp2
{{- else }}
  storageClassName: ""  
{{- end }}
  resources:
    requests:
      storage: {{ $storage }}
