apiVersion: batch/v1
kind: CronJob
metadata:
  name: word-id-cronjob
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: word-id-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: word-id-cronjob
            image: {{ printf "%s:%s" "trieve/word-id-cronjob" .Values.containers.word_id_cronjob.tag }}
            envFrom:
              - configMapRef:
                  name: trieve-server-config
