kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: trieve-postgresql-server
spec:
  enableSuperuserAccess: false
  instances: 2
  bootstrap:
    initdb:
      database: trieve
      owner: trieve
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi