apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: trieve-clickhouse
spec:
  configuration:
    users:
      default/password: "password" # todo
      # to allow access outside from kubernetes
      default/networks/ip:
        - 0.0.0.0/0
    clusters:
      - name: cluster1
        templates:
          podTemplate: clickhouse-pod-template
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          volumes:
            - name: trieve-clickhouse-initdb
              configMap:
                name: trieve-clickhouse-initdb
                defaultMode: 0555
          containers:
            - name: clickhouse
              image: trieve/clickhouse:latest
              digest: sha256:324f541975c43e96b5df6ede74632102d89172b703960bbf01f1842ccf48d240
              volumeMounts:
                - name: trieve-clickhouse-data
                  mountPath: /var/lib/clickhouse
                - name: trieve-clickhouse-logs
                  mountPath: /var/log/clickhouse-server
                - name: trieve-clickhouse-initdb
                  mountPath: /docker-entrypoint-initdb.d
                  readOnly: true
              env:
                - name: EMBEDDING_SERVER_URL
                  value: "" # todo
                - name: CLICKHOUSE_ADMIN_PASSWORD
                  value: "password" # todo

    volumeClaimTemplates:
      - name: trieve-clickhouse-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      - name: trieve-clickhouse-logs
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
