apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: trieve-clickhouse
spec:
  configuration:
    users:
      default/password: "password" # todo
      # to allow access outside from kubernetes
      default/networks/ip:
        - 0.0.0.0/0
    clusters:
      - name: cluster1
        templates:
          podTemplate: clickhouse-pod-template
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      user_scripts_path: /opt/user_scripts
      user_defined_executable_functions_config: /opt/user_functions/*_function.xml
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          volumes:
            - name: trieve-clickhouse-scripts
              configMap:
                name: trieve-clickhouse-scripts
                defaultMode: 0555
            - name: trieve-clickhouse-functions
              configMap:
                name: trieve-clickhouse-functions
                defaultMode: 0555
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.8
              volumeMounts:
                - name: trieve-clickhouse-userscripts
                  mountPath: /opt/user_scripts
                - name: trieve-clickhouse-data
                  mountPath: /var/lib/clickhouse
                - name: trieve-clickhouse-logs
                  mountPath: /var/log/clickhouse-server
                - name: trieve-clickhouse-scripts
                  mountPath: /docker-entrypoint-initdb.d
                  readOnly: true
                - name: trieve-clickhouse-functions
                  mountPath: /opt/user_functions/
                  readOnly: true
              env:
                - name: CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS
                  value: "true"
                - name: EMBEDDING_SERVER_URL
                  value: "http://trieve-embedding-bgem3" # todo
                - name: CLICKHOUSE_ADMIN_PASSWORD
                  value: "password" # todo

    volumeClaimTemplates:
      - name: trieve-clickhouse-userscripts
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: trieve-clickhouse-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      - name: trieve-clickhouse-logs
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi


