apiVersion: v1
kind: ConfigMap
metadata:
  name: trieve-clickhouse-functions
data:
  embedding_function.xml: |
    <functions>
      <function>
          <name>embed_p</name>
          <type>executable_pool</type>
          <pool_size>10</pool_size>
          <send_chunk_header>true</send_chunk_header>
          <format>TabSeparated</format>
          <return_type>Array(Float32)</return_type>
          <argument>
              <type>String</type>
          </argument>
          <command>/opt/user_scripts/embed.py</command>
      </function>
    </functions>
