resources:
  - clickhouse.yaml

configMapGenerator:
  - name: trieve-clickhouse-functions
    files:
      - embedding_function.xml
    options:
      disableNameSuffixHash: true

  - name: trieve-clickhouse-scripts
    files:
      - load_embed.sh
    options:
      disableNameSuffixHash: true