apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/pmig/trieve
        revision: pmig/gcp-trieve
        directories:
          - path: 'glasskube/packages/*'
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/pmig/trieve
        targetRevision: pmig/gcp-trieve
        path: '{{.path.path}}'
        kustomize:
          components:
            - ./
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
