apiVersion: batch/v1
kind: CronJob
metadata:
  name: trieve-word-id-cronjob
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: word-id-cronjob
              image: trieve/word-id-cronjob
              ports:
                - containerPort: 8090
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: trieve-db-cluster-app
                      key: uri
                - name: QDRANT_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: trieve-qdrant-qdrant-apikey
                      key: api-key
              envFrom:
                - configMapRef:
                    name: trieve-server-config
