apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trieve-keycloak
spec:
  rules:
    - host: auth.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-keycloak-service
                port:
                  number: 8080
