apiVersion: packages.glasskube.dev/v1alpha1
kind: Package
metadata:
  name: trieve-keycloak-db
spec:
  packageInfo:
    name: postgresql
    repositoryName: glasskube
    version: v16.4.0+2
  values:
    databaseName:
      value: keycloak
    enableSuperuserAccess:
      value: "false"
    instances:
      value: "1"
    memory:
      value: 256Mi
    storageSize:
      value: 10Gi
