apiVersion: v2
name: trieve-helm
description: Helm chart expressing Trieve deployment without any dependencies
type: application
version: 0.1.19
appVersion: "0.12.0"
dependencies:
  - name: qdrant
    repository: https://qdrant.github.io/qdrant-helm
    version: 1.13.4
    condition: qdrant.enabled
  - name: keycloak-operator
    repository: https://kbumsik.io/keycloak-kubernetes/
    version: 0.0.4
    condition: keycloak.enabled
  - name: altinity-clickhouse-operator
    repository: https://docs.altinity.com/clickhouse-operator/
    version: 0.24.4
    condition: clickhouse.enabled
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.23.0
    condition: postgres.enabled
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.10.0
    condition: redis.enabled
