environment: local # Set to aws if deploying to 
containers:
  server:
    tag: latest
    resources: {}
  ingest:
    tag: latest
    resources: {}
  file_worker:
    tag: latest
    resources: {}
  delete_worker:
    tag: latest
    resources: {}
  group_worker:
    tag: latest
    resources: {}
  sync_qdrant:
    tag: latest
    resources: {}
  bktree_worker:
    tag: latest
    resources: {}
  word_worker:
    tag: latest
    resources: {}
  word_id_cronjob:
    tag: latest
    resources: {}
  crawl_worker:
    tag: latest
    resources: {}
  ditto_feed_cronjob:
    tag: latest
    resources: {}
  clone_qdrant:
    tag: latest
    resources: {}
  search:
    tag: latest
    resources: {}
  chat:
    tag: latest
    resources: {}
  dashboard:
    tag: latest
    resources: {}
  clustering_cron:
    tag: latest
  clickhouse_collapse:
    tag: latest
domains:
  dashboard:
    host: dashbaord.localtrieve.com
    class: gce
  server:
    host: api.localtrieve.com
    class: gce
  search:
    host: search.localtrieve.com
    class: gce
  chat:
    host: chat.localtrieve.com
    class: gce
postgres:
  dbURI: 
config:
  vite:
    apiHost: https://api.localtrieve.com/api
    searchUiUrl: https://search.localtrieve.com
    chatUiUrl: https://chat.localtrieve.com
    dashboardUrl: https://dashboard.localtrieve.com
  redis:
    connections: 3
    uri: "redis://redis.default.svc.cluster.local:6379" 
  qdrant:
    qdrantUrl: http://trieve-qdrant.default.svc.cluster.local:6334
    apiKey: ""
    quantizeVectors: false  # If set to true will binary quantize
    replicationFactor: 2
    shardCount: 12
    vectorSizes:
      - 1024
  analytics:
    enabled: true
    clickhouseDB: "default"
    clickhouseUser: "default"
    clickhousePassword: "clickhouse"
    clickhouseUrl: "http://clickhouse-trieve-clickhouse.default.svc.cluster.local:8123" 
    clickhouseDSN: "clickhouse://default:clickhouse@clickhouse-trieve-clickhouse.default.svc.cluster.local/default"

  delete_worker:
    batch_size: 10000
  trieve:
    batch_limit: 120
    bm25Active: true
    unlimited: true
    cookieSecure: false
    baseServerUrl: https://dashbaord.localtrieve.com
    embeddingServerOrigin: http://embedding-jina.default.svc.cluster.local
    sparseServerQueryOrigin: http://embedding-splade-query.default.svc.cluster.local
    sparseServerDocOrigin: http://embedding-splade-doc.default.svc.cluster.local
    embeddingServerOriginBGEM3: http://embedding-m3.default.svc.cluster.local
    embeddingServerOriginJinaCode: https://api.jina.ai/v1
    jinaCodeApiKey: jina_************************************************************
    rerankerServerOrigin: http://embedding-reranker.default.svc.cluster.local
    salt: ""
    secretKey: ""
    adminApiKey: "admin"
    anthropicAPIKey: ""
    subtraceToken: ""
    firecrawlUrl: ""
    dittofeedApiKey: ""
  oidc:
    clientSecret: "YllmLDTy67MbsUBrUAWvQ7z9aMq0QcKx"
    clientId: "trieve"
    issuerUrl: "http://trieve-keycloak-service:8080/realms/trieve"
    authRedirectUrl: "http://trieve-keycloak-service:8080/realms/trieve/protocol/openid-connect/auth"
  smtp:
    relay: ""
    username: ""
    password: ""
    emailAddress: ""
  llm:
    apiKey: ""
  openai:
    apiKey: ""
    baseUrl: https://api.openai.com/v1
  s3:
    endpoint: ""
    accessKey: ""
    secretKey: ""
    bucket: ""
    region: ""
  stripe:
    secret: ""
    webhookSecret: ""
clone: {}
  # - origin: http://trieve-qdrant.default.svc.cluster.local:6334
  #   dest: http://qdrant-two.default.svc.cluster.local:6334
  #   collection: 768_vectors
  #   clone_name: 768
  #   timeout_ms: 50
  #   qdrant_timeout_sec: 60
embeddings: {}
  # - name: jina
  #   revision: main
  #   model: jinaai/jina-embeddings-v2-base-en
  #   args: []
  #   useGpu: true
  # - name: m3
  #   model: BAAI/bge-m3
  #   revision: main
  #   args: []
  # - name: reranker
  #   model: BAAI/bge-reranker-large
  #   revision: refs/pr/4
  #   args: []
  # - name: splade-doc
  #   model: naver/efficient-splade-VI-BT-large-doc
  #   revision: main
  #   args: ["--pooling", "splade"]
  # - name: splade-query
  #   model: naver/efficient-splade-VI-BT-large-query
  #   revision: main
  #   args: ["--pooling", "splade"]
