name: chat test suite

on: 
  push:
    paths:
      'chat/**'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up 
        run: sed -i 's/chat\///' ./chat/.eslintrc.json
      - name: Install dependencies
        run: yarn --cwd chat
      - name: Running lint
        run: yarn --cwd chat lint:CI
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: './chat/eslint_report.json'
