name: Frontends test suite

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "frontends/**"
      - "clients/ts-sdk/**"

jobs:
  build-test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Running Build
        run: yarn build
  eslint:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Running lint
        run: yarn lint:CI
      - name: Annotate Search Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0
        if: always()
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./frontends/search/eslint_report.json"
          fail-on-error: true
          fail-on-warning: true
      - name: Annotate Chat Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0
        if: always()
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./frontends/chat/eslint_report.json"
          fail-on-error: true
          fail-on-warning: true
      - name: Annotate Dashboard Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0
        if: always()
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./frontends/dashboard/eslint_report.json"
          fail-on-error: true
          fail-on-warning: true
