name: Create Docker Images
# Create Docker images tagged based off commit
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
  # workflow_dispatch:
  push:
  #   branches:
  #     - 'master'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  build_search:
    name: Building Search Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: search/
          file: ./Dockerfile
          push: true
          tags: ${{ vars.GITHUB_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
