name: Create Frontend Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "frontends/dashboard/**"
      - "frontends/search/**"
      - "frontends/chat/**"
      - "frontends/shared/**"
      - "frontends/config/**"
      - "clients/ts-sdk/**"

jobs:
  build_chat:
    name: Push Chat Image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2204-arm]
        platform: [linux/amd64, linux/arm64]
        include:
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: linux/amd64
            tag: latest
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: blacksmith-2vcpu-ubuntu-2204-arm
            tag: latest-arm
            suffix: -arm
        exclude:
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-2vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/chat
          tags: |
            type=raw,tag=${{matrix.tag}}
            type=sha,suffix=${{matrix.suffix}}

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: ${{ matrix.platform }}
          file: frontends/chat/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_search:
    name: Push Search Image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2204-arm]
        platform: [linux/amd64, linux/arm64]
        include:
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: linux/amd64
            tag: latest
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: blacksmith-2vcpu-ubuntu-2204-arm
            tag: latest-arm
            suffix: -arm
        exclude:
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-2vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/search
          tags: |
            type=raw,tag=${{matrix.tag}}
            type=sha,suffix=${{matrix.suffix}}

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: ${{ matrix.platform }}
          file: frontends/search/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_dashboard:
    name: Push Dashboard Image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2204-arm]
        platform: [linux/amd64, linux/arm64]
        include:
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: linux/amd64
            tag: latest
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: blacksmith-2vcpu-ubuntu-2204-arm
            tag: latest-arm
            suffix: -arm
        exclude:
          - runner: blacksmith-2vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-2vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/dashboard
          tags: |
            type=raw,tag=${{matrix.tag}}
            type=sha,suffix=${{matrix.suffix}}

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: ${{ matrix.platform }}
          file: frontends/dashboard/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
