name: Create Batch ETL images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "batch-etl/**"

jobs:
  build_server:
    name: Push Batch ETL Server image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: blacksmith-8vcpu-ubuntu-2204
            platform: linux/amd64
            tag: latest
            suffix: ""
          # - runner: blacksmith-8vcpu-ubuntu-2204
          #   platform: linux/arm64
          #   tag: latest-arm
          #   suffix: -arm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/batch-etl-server
          tags: |
            type=raw,${{matrix.tag}}

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: ${{ matrix.platform }}
          context: batch-etl/
          file: ./batch-etl/Dockerfile.server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  create-job-worker:
    name: Push Create Job image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: blacksmith-8vcpu-ubuntu-2204
            platform: linux/amd64
            tag: latest
          # - runner: blacksmith-8vcpu-ubuntu-2204
          #   platform: linux/arm64
          #   tag: latest-arm
          #   suffix: -arm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/create-job-worker
          tags: |
            type=raw,${{matrix.tag}}
            type=sha,suffix=${{matrix.suffix}}

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: ${{ matrix.platform }}
          context: batch-etl/
          file: ./batch-etl/Dockerfile.create-job-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  check-completion-worker:
    name: Push Check Completion worker
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: blacksmith-8vcpu-ubuntu-2204
            platform: linux/amd64
            tag: latest
          # - runner: blacksmith-8vcpu-ubuntu-2204
          #   platform: linux/arm64
          #   tag: latest-arm
          #   suffix: -arm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/check-completion-worker
          tags: |
            type=raw,${{matrix.tag}}
            type=sha,suffix=${{matrix.suffix}}

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: ${{ matrix.platform }}
          context: batch-etl/
          file: ./batch-etl/Dockerfile.check-completion-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
