name: search test suite

on: 
  push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up 
        run: sed -i 's/search\///' ./search/.eslintrc.json
      - name: Install dependencies
        run: yarn --cwd search/
      - name: Running lint
        run: yarn --cwd search lint:CI
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: './search/eslint_report.json'

